name: DreamApp CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Detect changes
    # Skip this job for PR closures
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      workflow: ${{ steps.filter.outputs.workflow }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50 # Ensure we have enough history for file changes detection
      
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
            workflow:
              - '.github/workflows/main.yml'

      - name: Print detected changes
        run: |
          echo "Frontend changes: ${{ steps.filter.outputs.frontend }}"
          echo "Backend changes: ${{ steps.filter.outputs.backend }}"
          echo "Workflow changes: ${{ steps.filter.outputs.workflow }}"

  build_and_deploy_frontend:
    needs: changes
    # Run if either:
    # 1. Changes detected in frontend files OR
    # 2. Workflow file changed OR
    # 3. Manual workflow dispatch
    if: >
      needs.changes.outputs.frontend == 'true' || 
      needs.changes.outputs.workflow == 'true' || 
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build and Deploy Frontend
        id: builddeployfrontend
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_WATER_0FB71A803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend" 
          api_location: "" 
          output_location: "dist"

  close_pull_request_frontend:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Frontend
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Close Frontend Pull Request
        id: closepullrequestfrontend
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_WATER_0FB71A803 }}
          action: "close"

  build_and_deploy_backend:
    needs: changes
    # Run if either:
    # 1. Changes detected in backend files OR
    # 2. Workflow file changed OR
    # 3. Manual workflow dispatch
    if: >
      needs.changes.outputs.backend == 'true' || 
      needs.changes.outputs.workflow == 'true' || 
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          # Make sure uvicorn is included in the artifact
          pip install uvicorn

      - name: Run tests
        run: |
          echo "Running tests..."
          # pytest

      - name: Update startup command
        run: |
          mkdir -p .azure
          echo '{
            "appCommandLine": "gunicorn app.main:app --bind=0.0.0.0:8000",
            "linuxFxVersion": "PYTHON|3.10"
          }' > .azure/config

          echo '{
            "extensions": [
              {
                "name": "Microsoft.SqlTools"
              }
            ]
          }' > .azure/site-extensions.json

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dreamapp-auth-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
